services:
  api-images:
    image: adenilsonkon/devopslabs01-api-images:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    networks:
      - default
  frontend:
    image: adenilsonkon/devopslabs01-frontend-api-images:latest
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - 5000:80
    depends_on:
      - api-images
    networks:
      - default
networks:
  default:
    driver: bridge