services:
  api-images:
    image: adenilsonkon/devopslabs01-api-images:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OTEL_SERVICE_NAME=api
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp

    ports:
      - 5001:5001
    networks:
      - default
  frontend:
    image: adenilsonkon/devopslabs01-frontend-api-images:latest
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - 5000:80
    depends_on:
      - api-images
    networks:
      - default

  otel:
    image: grafana/otel-lgtm
    ports:
      - 4317:4317
      - 4318:4318
      - 3000:3000
      - 9090:9090
networks:
  default:
    driver: bridge