name: Publish docker image on DockerHub

on:
  push: 
    branches: ["main" , "dev"]
  pull_request:
    branches: ["main" , "dev"]
  workflow_dispatch:
jobs:
  build:
    name: docker build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            adenilsonkon/devopslabs-api-images
          tags: |
            type=sha
            type=ref,event=branch,prefix=,suffix=-${{ github.sha }}
            
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ steps.meta.outputs.tags }}
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push the Docker image tag hash
        run: docker push ${{ steps.meta.outputs.tags }}
        
      - name: Push the Docker image tag latest
        run: docker tag ${{ steps.meta.outputs.tags }} adenilsonkon/devopslabs-api-images:latest && docker push adenilsonkon/devopslabs-api-images:latest
      
      - name: Atualiza tag no repositório OPS
        uses: actions/checkout@v4
        with: 
          repository: Adenilson365/devopslabs01-ops-api-images
          token: ${{ secrets.ACCESS_TOKEN_GIT }}
          ref: ${{ github.ref_name }}
          path: .

      - name: Atualiza tag no repositório OPS
        run: |
          pwd
          cat ./application/deployments/deployment.yaml
          sed -i "s|image: adenilsonkon/devopslabs-api-images:.*|image: adenilsonkon/devopslabs-api-images:${{ steps.meta.outputs.tags }}|g" ./application/deployments/deployment.yaml
          cat ./application/deployments/deployment.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_GIT }}
      - name: Commit and push changes
        run: | 
          pwd
          git config  user.name "GitHub Actions"
          git config  user.email "actions@github.com"
          git add .
          git diff --quiet && echo "Sem mudanças - Verifique o processo de build" && exit 0
          git commit -m "Atualiza tag do docker image para ${{ steps.meta.outputs.tags }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_GIT }}
